# Executes a build of the demo-project on jenkins running inside a docker container
# The build runs inside an agent-container, started by the jenkins-controller-container

name: jenkins started agent

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job starts a Jenkins server running inside a Docker container and builds the testproject
  buildOnJenkinsStartedAgent:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
       matrix:
          java: [ 1.8, 11, 15 ]
       fail-fast: false

    defaults:
      run:
        working-directory: buildOnJenkinsStartedAgent

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+02:00"
    - name: Print current time
      env:
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      run: echo $R_TIME
    - name: Build peass and peass-ci
      run: ../common/scripts/buildPeassAndPeassCI.sh
    - name: Build and run container
      run: ./buildOnJenkinsStartedAgent.sh
    - name: Wait for jenkins startup
      run: ./waitForJenkinsStartup.sh
    - name: Wait for build end
      run: ./waitForBuildEnd.sh
    - name: Check results
      run: ./checkResults.sh

  sendMailOnFailure:
    needs: [buildOnJenkinsStartedAgent]
    if: success() != true
    runs-on: ubuntu-latest
    steps:
    - name: Send email on failure
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: studserv.uni-leipzig.de
        # Required mail server port:
        server_port: 25
        # Required mail server username:
        username: ${{ secrets.MAIL_USERNAME }}
        # Required mail server password:
        password: ${{ secrets.MAIL_PASSWORD }}
        # Required mail subject:
        subject: Workflow "${{ github.workflow }}" on ${{ github.repository }} failed!
        # email body:
        body: Run https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} of workflow "${{ github.workflow }}" failed!
        # Required recipients' addresses:
        to: ${{ secrets.MAIL_DAGERE }}
        # Required sender full name (address can be skipped):
        from: ${{ secrets.NAME_MW }} <${{ secrets.MAIL_USERNAME_UNI }}@uni-leipzig.de>
