# Executes a build of the demo-project on jenkins running inside a docker container
# The build runs inside a manually started and registered agent-container
# Uses peass and peass-ci develop-branches

name: manually started agent, peass(-ci)-develop

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job starts a Jenkins server running inside a Docker container and builds the testproject
  buildOnManuallyStartedAgentDevelop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
       matrix:
          java: [ 1.8, 11, 15 ]
       fail-fast: false

    defaults:
      run:
        working-directory: buildOnManuallyStartedAgent

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+02:00"
    - name: Print current time
      env:
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      run: echo $R_TIME
    - name: Build peass(-ci)-develop
      run: ../common/scripts/buildPeassAndPeassCI-develop.sh
    - name: Build and run container
      run: ./buildOnManuallyStartedAgent.sh
    - name: Wait for jenkins startup
      run: ./waitForJenkinsStartup.sh
    - name: Register agent to controller
      run: ./registerAgentToController.sh
    - name: Wait for build end
      run: ./waitForBuildEnd.sh
    - name: Check results
      run: ./checkResults.sh
